### ISSUE TITLE
Obsidian not yet available on Hints

### ISSUE THREAD

**Issue by kmaustral** [slpbx/obsidian-plugin#1]
![image](https://user-images.githubusercontent.com/73867063/209025900-9d821b62-68bc-4298-a9b5-0d2ab1d10c8b.png)

**Comment by neoantox** [comment]
Hi, @kmaustral! We've just released an update. Obsidian is now available on [Hints](https://i.hints.so)
<img width="389" alt="image" src="https://user-images.githubusercontent.com/134825/209121248-6413afc1-30bc-403a-ad02-6e808b9323c3.png">
